# Generated by Django 4.0.5 on 2022-06-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=200)),
                ('num_tlf', models.BigIntegerField()),
                ('sexe', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
